ENGLISH_FRENCH_COUNTRY_MAPPER = {
    # a
    "afghanistan": "Afghanistan",
    "albania": "Albanie",
    "algeria": "Algérie",
    "andorra": "Andorre",
    "angola": "Angola",
    "antigua and Barbuda": "Antigua-et-Barbuda",
    "argentina": "Argentine",
    "armenia": "Arménie",
    "australia": "Australie",
    "austria": "Autriche",
    "azerbaijan": "Azerbaïdjan",
    # b
    "bahamas": "Bahamas",
    "bahrain": "Bahreïn",
    "bangladesh": "Bangladesh",
    "barbados": "Barbade",
    "belarus": "Biélorussie",
    "belgium": "Belgique",
    "belize": "Belize",
    "benin": "Bénin",
    "bhutan": "Bhoutan",
    "bolivia": "Bolivie",
    "bosnia and Herzegovina": "Bosnie-Herzégovine",
    "botswana": "Botswana",
    "brazil": "Brésil",
    "brunei": "Brunei",
    "bulgaria": "Bulgarie",
    "burkina faso": "Burkina Faso",
    "burundi": "Burundi",
    # c
    "cabo verde": "Cap-Vert",
    "cambodia": "Cambodge",
    "cameroon": "Cameroun",
    "canada": "Canada",
    "central african Republic": "République centrafricaine",
    "chad": "Tchad",
    "chile": "Chili",
    "china": "Chine",
    "colombia": "Colombie",
    "comoros": "Comores",
    "congo": "Congo",
    "costa rica": "Costa Rica",
    "croatia": "Croatie",
    "cuba": "Cuba",
    "cyprus": "Chypre",
    "czech republic": "République tchèque",
    # d
    "denmark": "Danemark",
    "djibouti": "Djibouti",
    "dominica": "Dominique",
    "dominican republic": "République dominicaine",
    # e
    "ecuador": "Équateur",
    "egypt": "Égypte",
    "el salvador": "Salvador",
    "equatorial guinea": "Guinée équatoriale",
    "eritrea": "Érythrée",
    "estonia": "Estonie",
    "eswatini": "Eswatini",
    "ethiopia": "Éthiopie",
    # f
    "fiji": "Fidji",
    "finland": "Finlande",
    "france": "France",
    # g
    "gabon": "Gabon",
    "gambia": "Gambie",
    "georgia": "Géorgie",
    "germany": "Allemagne",
    "ghana": "Ghana",
    "greece": "Grèce",
    "grenada": "Grenade",
    "guatemala": "Guatemala",
    "guinea": "Guinée",
    "guinea-bissau": "Guinée-Bissau",
    "guyana": "Guyana",
    # h
    "haiti": "Haïti",
    "honduras": "Honduras",
    "hungary": "Hongrie",
    # i
    "iceland": "Islande",
    "india": "Inde",
    "indonesia": "Indonésie",
    "iran": "Iran",
    "iraq": "Irak",
    "ireland": "Irlande",
    "israel": "Israël",
    "italy": "Italie",
    # j
    "jamaica": "Jamaïque",
    "japan": "Japon",
    "jordan": "Jordanie",
    # k
    "kazakhstan": "Kazakhstan",
    "kenya": "Kenya",
    "kiribati": "Kiribati",
    "korea, North": "Corée du Nord",
    "korea, South": "Corée du Sud",
    "kosovo": "Kosovo",
    "kuwait": "Koweït",
    "kyrgyzstan": "Kirghizistan",
    # l
    "laos": "Laos",
    "latvia": "Lettonie",
    "lebanon": "Liban",
    "lesotho": "Lesotho",
    "liberia": "Libéria",
    "libya": "Libye",
    "liechtenstein": "Liechtenstein",
    "lithuania": "Lituanie",
    "luxembourg": "Luxembourg",
    # m
    "madagascar": "Madagascar",
    "malawi": "Malawi",
    "malaysia": "Malaisie",
    "maldives": "Maldives",
    "mali": "Mali",
    "malta": "Malte",
    "marshall islands": "Îles Marshall",
    "mauritania": "Mauritanie",
    "mauritius": "Maurice",
    "mexico": "Mexique",
    "micronesia": "Micronésie",
    "moldova": "Moldavie",
    "monaco": "Monaco",
    "mongolia": "Mongolie",
    "montenegro": "Monténégro",
    "morocco": "Maroc",
    "mozambique": "Mozambique",
    "myanmar": "Myanmar",
    # n
    "namibia": "Namibie",
    "nauru": "Nauru",
    "nepal": "Népal",
    "netherlands": "Pays-Bas",
    "new zealand": "Nouvelle-Zélande",
    "nicaragua": "Nicaragua",
    "niger": "Niger",
    "nigeria": "Nigéria",
    "north macedonia": "Macédoine du Nord",
    "norway": "Norvège",
    # o
    "oman": "Oman",
    # p
    "pakistan": "Pakistan",
    "palau": "Palaos",
    "panama": "Panama",
    "papua new Guinea": "Papouasie-Nouvelle-Guinée",
    "paraguay": "Paraguay",
    "peru": "Pérou",
    "philippines": "Philippines",
    "poland": "Pologne",
    "portugal": "Portugal",
    # q
    "qatar": "Qatar",
    # r
    "romania": "Roumanie",
    "russia": "Russie",
    "rwanda": "Rwanda",
    # s
    "saint kitts and Nevis": "Saint-Christophe-et-Niévès",
    "saint lucia": "Sainte-Lucie",
    "saint vincent and the Grenadines": "Saint-Vincent-et-les-Grenadines",
    "samoa": "Samoa",
    "san marino": "Saint-Marin",
    "sao tome and Principe": "Sao Tomé-et-Principe",
    "saudi arabia": "Arabie saoudite",
    "senegal": "Sénégal",
    "serbia": "Serbie",
    "seychelles": "Seychelles",
    "sierra leone": "Sierra Leone",
    "singapore": "Singapour",
    "slovakia": "Slovaquie",
    "slovenia": "Slovénie",
    "solomon islands": "Îles Salomon",
    "somalia": "Somalie",
    "south africa": "Afrique du Sud",
    "south sudan": "Soudan du Sud",
    "spain": "Espagne",
    "sri lanka": "Sri Lanka",
    "sudan": "Soudan",
    "suriname": "Suriname",
    "sweden": "Suède",
    "switzerland": "Suisse",
    "syria": "Syrie",
    # t
    "taiwan": "Taïwan",
    "tajikistan": "Tadjikistan",
    "tanzania": "Tanzanie",
    "thailand": "Thaïlande",
    "timor-leste": "Timor oriental",
    "togo": "Togo",
    "tonga": "Tonga",
    "trinidad and Tobago": "Trinité-et-Tobago",
    "tunisia": "Tunisie",
    "turkey": "Turquie",
    "turkmenistan": "Turkménistan",
    "tuvalu": "Tuvalu",
    # u
    "uganda": "Ouganda",
    "ukraine": "Ukraine",
    "united arab Emirates": "Émirats arabes unis",
    "united kingdom": "Royaume-Uni",
    "united states": "États-Unis",
    "uruguay": "Uruguay",
    "uzbekistan": "Ouzbékistan",
    # v
    "vanuatu": "Vanuatu",
    "vatican city": "Vatican",
    "venezuela": "Venezuela",
    "vietnam": "Vietnam",
    # y
    "yemen": "Yémen",
    # z
    "zambia": "Zambie",
    "zimbabwe": "Zimbabwe",
}
