from openfoodfacts_exports.exports.parquet.food import FoodProduct
import pytest


# nutrition as sold per 100g
NUTRITION_1 = {
    "aggregated_set": {
        "nutrients": {
            "salt": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "serving",
                "unit": "g",
                "value": 0.5,
            },
            "saturated-fat": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "serving",
                "unit": "g",
                "value": 0.5,
            },
        },
        "per": "100g",
        "preparation": "as_sold",
    },
    "input_sets": [
        {
            "nutrients": {
                "salt": {"unit": "g", "value": 1, "value_string": "1"},
                "saturated-fat": {
                    "unit": "g",
                    "value": 1,
                    "value_string": "1",
                },
            },
            "per": "serving",
            "per_quantity": 200,
            "per_unit": "g",
            "preparation": "as_sold",
            "source": "packaging",
        }
    ],
}


# nutrition for prepared food per 100g
NUTRITION_2 = {
    "aggregated_set": {
        "nutrients": {
            "carbohydrates": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 81.4,
            },
            "energy": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "kJ",
                "value": 1549,
            },
            "energy-kcal": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "kcal",
                "value": 366,
            },
            "energy-kj": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "kJ",
                "value": 1549,
            },
            "fat": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0.5,
            },
            "fiber": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 8,
            },
            "proteins": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 5.1,
            },
            "salt": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0.23,
            },
            "saturated-fat": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0.2,
            },
            "sodium": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0.092,
            },
            "sugars": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 4.4,
            },
        },
        "per": "100g",
        "preparation": "prepared",
    },
    "input_sets": [
        {
            "last_updated_t": 1770737625,
            "nutrients": {
                "carbohydrates": {"unit": "g", "value": 81.4, "value_string": "81.4"},
                "energy-kcal": {"unit": "kcal", "value": 366, "value_string": "366"},
                "energy-kj": {"unit": "kJ", "value": 1549, "value_string": "1549"},
                "fat": {"unit": "g", "value": 0.5, "value_string": "0.5"},
                "fiber": {"unit": "g", "value": 8, "value_string": "8"},
                "proteins": {"unit": "g", "value": 5.1, "value_string": "5.1"},
                "salt": {"unit": "g", "value": 0.23, "value_string": "0.23"},
                "saturated-fat": {"unit": "g", "value": 0.2, "value_string": "0.2"},
                "sodium": {"unit": "g", "value": 0.092, "value_string": "0.092"},
                "sugars": {"unit": "g", "value": 4.4, "value_string": "4.4"},
            },
            "per": "100g",
            "per_quantity": 100,
            "per_unit": "g",
            "preparation": "prepared",
            "source": "packaging",
        },
        {
            "last_updated_t": 1770737625,
            "nutrients": {
                "carbohydrates": {"unit": "g", "value": 83, "value_string": "83"},
                "energy-kcal": {"unit": "kcal", "value": 371, "value_string": "371"},
                "energy-kj": {"unit": "kJ", "value": 1573, "value_string": "1573"},
                "fat": {"unit": "g", "value": 0.3, "value_string": "0.3"},
                "fiber": {"unit": "g", "value": 8, "value_string": "8"},
                "nova-group": {"unit": "g", "value": 1, "value_string": "1"},
                "proteins": {"unit": "g", "value": 5.1, "value_string": "5.1"},
                "salt": {"unit": "g", "value": 0.23, "value_string": "0.23"},
                "saturated-fat": {"unit": "g", "value": 0.2, "value_string": "0.2"},
                "sodium": {"unit": "g", "value": 0.092, "value_string": "0.092"},
                "sugars": {"unit": "g", "value": 3.2, "value_string": "3.2"},
            },
            "per": "100g",
            "per_quantity": 100,
            "per_unit": "g",
            "preparation": "as_sold",
            "source": "packaging",
        },
    ],
}

NUTRITION_3 = {
    "aggregated_set": {
        "nutrients": {
            "carbohydrates": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0.5,
            },
            "energy": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "kJ",
                "value": 14,
                "value_computed": 21.0,
            },
            "energy-kcal": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "kcal",
                "value": 3,
                "value_computed": 5,
            },
            "energy-kj": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "kJ",
                "value": 14,
                "value_computed": 21.0,
            },
            "fat": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0,
            },
            "fiber": {
                "modifier": "<",
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0.5,
            },
            "proteins": {
                "modifier": "<",
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0.5,
            },
            "salt": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0,
                "value_computed": 0,
            },
            "saturated-fat": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0,
            },
            "sodium": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0,
                "value_computed": 0,
            },
            "sugars": {
                "source": "packaging",
                "source_index": 0,
                "source_per": "100g",
                "unit": "g",
                "value": 0,
            },
        },
        "per": "100g",
        "preparation": "prepared",
    },
    "input_sets": [
        {
            "last_updated_t": 1770974282,
            "nutrients": {
                "carbohydrates": {
                    "unit": "g",
                    "value": 0.5,
                    "value_string": "0.5",
                },
                "energy-kcal": {
                    "unit": "kcal",
                    "value": 3,
                    "value_computed": 5,
                    "value_string": "3",
                },
                "energy-kj": {
                    "unit": "kJ",
                    "value": 14,
                    "value_computed": 21.0,
                    "value_string": "14",
                },
                "fat": {"unit": "g", "value": 0, "value_string": "0"},
                "fiber": {
                    "modifier": "<",
                    "unit": "g",
                    "value": 0.5,
                    "value_string": "0.5",
                },
                "proteins": {
                    "modifier": "<",
                    "unit": "g",
                    "value": 0.5,
                    "value_string": "0.5",
                },
                "salt": {
                    "unit": "g",
                    "value": 0,
                    "value_computed": 0,
                    "value_string": "0",
                },
                "saturated-fat": {"unit": "g", "value": 0, "value_string": "0"},
                "sodium": {
                    "unit": "g",
                    "value": 0,
                    "value_computed": 0,
                    "value_string": "0",
                },
                "sugars": {"unit": "g", "value": 0, "value_string": "0"},
            },
            "per": "100g",
            "per_quantity": 100,
            "per_unit": "g",
            "preparation": "prepared",
            "source": "packaging",
        },
        {
            "nutrients": {
                "carbohydrates": {"unit": "g", "value": 1, "value_string": "1"},
                "energy-kcal": {
                    "unit": "kcal",
                    "value": 6,
                    "value_computed": 7,
                    "value_string": "6",
                },
                "energy-kj": {
                    "unit": "kJ",
                    "value": 27,
                    "value_computed": 29.5,
                    "value_string": "27",
                },
                "fat": {"unit": "g", "value": 0, "value_string": "0"},
                "fiber": {
                    "modifier": "<",
                    "unit": "g",
                    "value": 0.5,
                    "value_string": "0.5",
                },
                "proteins": {
                    "modifier": "<",
                    "unit": "g",
                    "value": 0.5,
                    "value_string": "0.5",
                },
                "salt": {"unit": "g", "value": 0, "value_string": "0"},
                "saturated-fat": {"unit": "g", "value": 0, "value_string": "0"},
                "sodium": {"unit": "g", "value_computed": 0},
                "sugars": {"unit": "g", "value": 0, "value_string": "0"},
            },
            "per": "serving",
            "per_quantity": 200,
            "per_unit": "ml",
            "preparation": "prepared",
            "source": "packaging",
        },
        {
            "last_updated_t": 1770974282,
            "nutrients": {"nova-group": {"unit": "g", "value": 4, "value_string": "4"}},
            "per": "100g",
            "per_quantity": 100,
            "per_unit": "g",
            "preparation": "as_sold",
            "source": "packaging",
        },
        {
            "nutrients": {
                "added-sugars": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0,
                    "value_string": "0",
                },
                "alcohol": {
                    "modifier": "~",
                    "unit": "% vol",
                    "value": 0,
                    "value_string": "0",
                },
                "calcium": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.117,
                    "value_string": "0.117",
                },
                "carbohydrates": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 39.195,
                    "value_string": "39.195",
                },
                "cholesterol": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0,
                    "value_string": "0",
                },
                "copper": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.00151125,
                    "value_string": "0.00151125",
                },
                "energy": {
                    "modifier": "~",
                    "unit": "kJ",
                    "value": 387.075,
                    "value_string": "387.075",
                },
                "energy-kcal": {"unit": "kcal", "value_computed": 386.685},
                "energy-kj": {"unit": "kJ", "value_computed": 1614.99},
                "fat": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 15.015,
                    "value_string": "15.015",
                },
                "fiber": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 19.305,
                    "value_string": "19.305",
                },
                "fruits-vegetables-legumes": {
                    "modifier": "~",
                    "unit": "%",
                    "value": 0,
                    "value_string": "0",
                },
                "fruits-vegetables-nuts": {
                    "modifier": "~",
                    "unit": "%",
                    "value": 0,
                    "value_string": "0",
                },
                "iron": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.0039975,
                    "value_string": "0.0039975",
                },
                "magnesium": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.234,
                    "value_string": "0.234",
                },
                "manganese": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.00207675,
                    "value_string": "0.00207675",
                },
                "phosphorus": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.156,
                    "value_string": "0.156",
                },
                "polyols": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0,
                    "value_string": "0",
                },
                "potassium": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 1.9695,
                    "value_string": "1.9695",
                },
                "proteins": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 14.04,
                    "value_string": "14.04",
                },
                "salt": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.18525,
                    "value_computed": 0.180375,
                    "value_string": "0.18525",
                },
                "sodium": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.07215,
                    "value_computed": 0.0741,
                    "value_string": "0.07215",
                },
                "vitamin-b6": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 9.75e-07,
                    "value_string": "9.75e-07",
                },
                "vitamin-c": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0,
                    "value_string": "0",
                },
                "vitamin-e": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.0026325,
                    "value_string": "0.0026325",
                },
                "water": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 5.3625,
                    "value_string": "5.3625",
                },
                "zinc": {
                    "modifier": "~",
                    "unit": "g",
                    "value": 0.00077025,
                    "value_string": "0.00077025",
                },
            },
            "per": "100g",
            "per_quantity": 100,
            "per_unit": "g",
            "preparation": "as_sold",
            "source": "estimate",
            "source_description": "Estimate from ingredients",
        },
    ],
}


class TestFoodProduct:
    @pytest.mark.parametrize(
        "data,expected",
        [
            ({"schema_version": 999, "nutriments": {}}, None),
            (
                {"schema_version": 1003, "nutrition": NUTRITION_1},
                [
                    {
                        "100g": 0.5,
                        "name": "salt",
                        "prepared_100g": None,
                        "prepared_serving": None,
                        "prepared_unit": None,
                        "prepared_value": None,
                        "serving": None,
                        "unit": "g",
                        "value": None,
                    },
                    {
                        "100g": 0.5,
                        "name": "saturated-fat",
                        "prepared_100g": None,
                        "prepared_serving": None,
                        "prepared_unit": None,
                        "prepared_value": None,
                        "serving": None,
                        "unit": "g",
                        "value": None,
                    },
                ],
            ),
            (
                {"schema_version": 1003, "nutrition": NUTRITION_2},
                [
                    {
                        "100g": None,
                        "name": "carbohydrates",
                        "prepared_100g": 81.4,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "energy",
                        "prepared_100g": 1549.0,
                        "prepared_serving": None,
                        "prepared_unit": "kJ",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "energy-kcal",
                        "prepared_100g": 366.0,
                        "prepared_serving": None,
                        "prepared_unit": "kcal",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "energy-kj",
                        "prepared_100g": 1549.0,
                        "prepared_serving": None,
                        "prepared_unit": "kJ",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "fat",
                        "prepared_100g": 0.5,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "fiber",
                        "prepared_100g": 8.0,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "proteins",
                        "prepared_100g": 5.1,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "salt",
                        "prepared_100g": 0.23,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "saturated-fat",
                        "prepared_100g": 0.2,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "sodium",
                        "prepared_100g": 0.092,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "sugars",
                        "prepared_100g": 4.4,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                ],
            ),
            (
                {"schema_version": 1003, "nutrition": NUTRITION_3},
                [
                    {
                        "100g": None,
                        "name": "carbohydrates",
                        "prepared_100g": 0.5,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "energy",
                        "prepared_100g": 14.0,
                        "prepared_serving": None,
                        "prepared_unit": "kJ",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "energy-kcal",
                        "prepared_100g": 3.0,
                        "prepared_serving": None,
                        "prepared_unit": "kcal",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "energy-kj",
                        "prepared_100g": 14.0,
                        "prepared_serving": None,
                        "prepared_unit": "kJ",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "fat",
                        "prepared_100g": 0.0,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "fiber",
                        "prepared_100g": 0.5,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "proteins",
                        "prepared_100g": 0.5,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "salt",
                        "prepared_100g": 0.0,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "saturated-fat",
                        "prepared_100g": 0.0,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "sodium",
                        "prepared_100g": 0.0,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                    {
                        "100g": None,
                        "name": "sugars",
                        "prepared_100g": 0.0,
                        "prepared_serving": None,
                        "prepared_unit": "g",
                        "prepared_value": None,
                        "serving": None,
                        "unit": None,
                        "value": None,
                    },
                ],
            ),
        ],
    )
    def test_parse_nutriments(self, data, expected):
        output = FoodProduct.parse_nutriments(data)
        assert output["nutriments"] == expected
